/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type RoomCode = string;
export interface RoomView {
  'participants' : Array<UserId>,
  'code' : RoomCode,
  'createdAt' : Time,
}
export interface Signal { 'to' : UserId, 'data' : SignalData, 'from' : UserId }
export type SignalData = string;
export type Time = bigint;
export type UserId = string;
export interface _SERVICE {
  'clearSignals' : ActorMethod<[RoomCode, UserId], undefined>,
  'createRoom' : ActorMethod<[RoomCode], undefined>,
  'getAllRooms' : ActorMethod<[], Array<RoomView>>,
  'getAllSignals' : ActorMethod<[], Array<[[RoomCode, UserId], Array<Signal>]>>,
  'getPendingSignals' : ActorMethod<[RoomCode, UserId], Array<Signal>>,
  'getRoomInfo' : ActorMethod<[RoomCode], RoomView>,
  'isParticipant' : ActorMethod<[RoomCode, UserId], boolean>,
  'joinRoom' : ActorMethod<[RoomCode, UserId], undefined>,
  'leaveRoom' : ActorMethod<[RoomCode, UserId], undefined>,
  'sendSignal' : ActorMethod<[RoomCode, UserId, UserId, SignalData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];