/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomCode = IDL.Text;
export const UserId = IDL.Text;
export const Time = IDL.Int;
export const RoomView = IDL.Record({
  'participants' : IDL.Vec(UserId),
  'code' : RoomCode,
  'createdAt' : Time,
});
export const SignalData = IDL.Text;
export const Signal = IDL.Record({
  'to' : UserId,
  'data' : SignalData,
  'from' : UserId,
});

export const idlService = IDL.Service({
  'clearSignals' : IDL.Func([RoomCode, UserId], [], []),
  'createRoom' : IDL.Func([RoomCode], [], []),
  'getAllRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getAllSignals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Tuple(RoomCode, UserId), IDL.Vec(Signal)))],
      ['query'],
    ),
  'getPendingSignals' : IDL.Func(
      [RoomCode, UserId],
      [IDL.Vec(Signal)],
      ['query'],
    ),
  'getRoomInfo' : IDL.Func([RoomCode], [RoomView], ['query']),
  'isParticipant' : IDL.Func([RoomCode, UserId], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([RoomCode, UserId], [], []),
  'leaveRoom' : IDL.Func([RoomCode, UserId], [], []),
  'sendSignal' : IDL.Func([RoomCode, UserId, UserId, SignalData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomCode = IDL.Text;
  const UserId = IDL.Text;
  const Time = IDL.Int;
  const RoomView = IDL.Record({
    'participants' : IDL.Vec(UserId),
    'code' : RoomCode,
    'createdAt' : Time,
  });
  const SignalData = IDL.Text;
  const Signal = IDL.Record({
    'to' : UserId,
    'data' : SignalData,
    'from' : UserId,
  });
  
  return IDL.Service({
    'clearSignals' : IDL.Func([RoomCode, UserId], [], []),
    'createRoom' : IDL.Func([RoomCode], [], []),
    'getAllRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getAllSignals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Tuple(RoomCode, UserId), IDL.Vec(Signal)))],
        ['query'],
      ),
    'getPendingSignals' : IDL.Func(
        [RoomCode, UserId],
        [IDL.Vec(Signal)],
        ['query'],
      ),
    'getRoomInfo' : IDL.Func([RoomCode], [RoomView], ['query']),
    'isParticipant' : IDL.Func([RoomCode, UserId], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([RoomCode, UserId], [], []),
    'leaveRoom' : IDL.Func([RoomCode, UserId], [], []),
    'sendSignal' : IDL.Func([RoomCode, UserId, UserId, SignalData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };