/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SignalData = string;
export type UserId = string;
export interface Signal {
    to: UserId;
    data: SignalData;
    from: UserId;
}
export type Time = bigint;
export interface RoomView {
    participants: Array<UserId>;
    code: RoomCode;
    createdAt: Time;
}
export type RoomCode = string;
export interface backendInterface {
    clearSignals(roomCode: RoomCode, userId: UserId): Promise<void>;
    createRoom(code: RoomCode): Promise<void>;
    getAllRooms(): Promise<Array<RoomView>>;
    getAllSignals(): Promise<Array<[[RoomCode, UserId], Array<Signal>]>>;
    getPendingSignals(roomCode: RoomCode, userId: UserId): Promise<Array<Signal>>;
    getRoomInfo(code: RoomCode): Promise<RoomView>;
    isParticipant(roomCode: RoomCode, userId: UserId): Promise<boolean>;
    joinRoom(code: RoomCode, userId: UserId): Promise<void>;
    leaveRoom(code: RoomCode, userId: UserId): Promise<void>;
    sendSignal(roomCode: RoomCode, from: UserId, to: UserId, data: SignalData): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearSignals(arg0: RoomCode, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSignals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSignals(arg0, arg1);
            return result;
        }
    }
    async createRoom(arg0: RoomCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0);
            return result;
        }
    }
    async getAllRooms(): Promise<Array<RoomView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return result;
        }
    }
    async getAllSignals(): Promise<Array<[[RoomCode, UserId], Array<Signal>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return result;
        }
    }
    async getPendingSignals(arg0: RoomCode, arg1: UserId): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSignals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSignals(arg0, arg1);
            return result;
        }
    }
    async getRoomInfo(arg0: RoomCode): Promise<RoomView> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomInfo(arg0);
            return result;
        }
    }
    async isParticipant(arg0: RoomCode, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isParticipant(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isParticipant(arg0, arg1);
            return result;
        }
    }
    async joinRoom(arg0: RoomCode, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1);
            return result;
        }
    }
    async leaveRoom(arg0: RoomCode, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0, arg1);
            return result;
        }
    }
    async sendSignal(arg0: RoomCode, arg1: UserId, arg2: UserId, arg3: SignalData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSignal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSignal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
